name: continue_on_error
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: latest
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-key-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: run lint 
        run: npm run lint 
      - name: run test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: latest
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: dep-key-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: build jobs
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-file
          path: dist
      - name: list files 
        run: ls -R dist
      - name: deploy
        run: echo "deploying...."