name: deployment3
on: 
  push:
    branches:
      - main
  workflow_dispatch:
env: 
    PORT: 8080
jobs:
  secrets:
    env:
      DB_USER: ${{ vars.db_user }}
      DB_PASS: ${{ secrets.db_pass }}
      PORT: 5000
    runs-on: ubuntu-latest
    steps:
      - name: credentials
        run: |
          echo "DB_USER: $DB_USER"
          echo "DB_PASS: $DB_PASS"
          echo "PORT: $PORT"
  
  dev: 
    environment: development
    env:
      DB_USER: ${{ vars.db_user }}
      DB_PASS: ${{ secrets.db_pass }}
      PORT: 6000
    runs-on: ubuntu-latest
    steps:
      
      - name: credentials
        env:
          PORT: 7000
        run: |
          echo "DB_USER: $DB_USER"
          echo "DB_PASS: $DB_PASS"
          echo "PORT: $PORT"
  
  prod:
    environment: production
    env:
      DB_USER: ${{ vars.db_user }}
      DB_PASS: ${{ secrets.db_pass }}
    runs-on: ubuntu-latest
    steps:
      - name: credentials
        run: |
          echo "DB_USER: ${{ env.DB_USER }}"
          echo "DB_PASS: ${{ env.DB_PASS }}"
          echo "PORT: ${{ env.PORT }}"